language: python

sudo: false

env:
    - TOX_ENV=py35-django211
    - TOX_ENV=py36-django211
    - TOX_ENV=coverage_combine
    - TOX_ENV=docs

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=coverage_combine
    - env: TOX_ENV=docs
    - env: TOX_ENV=py35-django211

before_install:
    - pip install pytest pytest-cov
    - pip install coveralls

install:
  - pip install tox

script:
    - tox -e $TOX_ENV

after_success:
    - coveralls

notifications:
    email:
        - alainivars@gmail.com
