dist: xenial
language: python
python:
  - "3.8"

sudo: false

env:
    - TOX_ENV=pep8
    - TOX_ENV=py38-django31
    - TOX_ENV=docs

matrix:
  #fast_finish: true
  allow_failures:
    - env: TOX_ENV=pep8
    - env: TOX_ENV=coverage_combine
    - env: TOX_ENV=docs

before_install:
    - pip install pytest pytest-cov
    - pip install coveralls

install:
    - pip install tox

script:
    - tox -e $TOX_ENV

after_success:
    - coveralls

notifications:
    email:
        - alainivars@gmail.com
