#
# The doc: https://docs.docker.com/engine/reference/builder/#usage
# The origin: https://medium.com/bitcraft/docker-composing-a-python-3-flask-app-line-by-line-93b721105777
#
# Dockerfile-nginx

FROM nginx:latest

# Nginx will listen on this port
EXPOSE 80

# Remove the default config file that
# /etc/nginx/nginx.conf includes
RUN rm /etc/nginx/conf.d/default.conf

# We copy the requirements file in order to install
# Python dependencies
COPY app.conf /etc/nginx/conf.d