version: '3.7'

services:

  db-pg:
    image: library/postgres:12.4
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  drf-ms-pg:
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - SECRET_KEY=${SECRET_KEY}
      - ENABLE_DEBUG=0
      - DOCKER_CONTAINER=1
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    image: drf-ms-pg:latest
#    build: ""
    command: >
      bash -c "sleep 5 &&
              ./manage.py makemigrations &&
              ./manage.py migrate --noinput &&
              ./manage.py collectstatic --noinput &&
              ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - db-pg

volumes:
  postgres_data:
