
.. _`Cookiescutter-drf-microservice`: https://github.com/alainivars/cookiecutter-drf-microservice
.. _`Drf-microservice`: https://github.com/alainivars/drf-microservice
.. _`Issue Cookiescutter-drf-microservice`: https://github.com/alainivars/cookiecutter-drf-microservice/issues
.. _`Issue Drf-microservice`: https://github.com/alainivars/drf-microservice/issues
.. _`readthedoc`: https://drf-microservice.readthedocs.io/en/latest/
